server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  zipkin:
    base-url: ${ZIPKIN_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,busrefresh,refresh,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 0.5
