server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata
  zipkin:
    base-url: ${ZIPKIN_URL}
management:
  endpoints:
    web:
      exposure:
        include: health,info,busrefresh,refresh,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 0.5
