server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata

management:
  endpoints:
    web:
      exposure:
        include: health,info,busrefresh,refresh
  tracing:
    sampling:
      probability: 1.0
